export const transportsParis = {
  metro: [
    { value: "METRO_1", label: "Métro — Ligne 1" },
    { value: "METRO_2", label: "Métro — Ligne 2" },
    { value: "METRO_3", label: "Métro — Ligne 3" },
    { value: "METRO_3BIS", label: "Métro — Ligne 3bis" },
    { value: "METRO_4", label: "Métro — Ligne 4" },
    { value: "METRO_5", label: "Métro — Ligne 5" },
    { value: "METRO_6", label: "Métro — Ligne 6" },
    { value: "METRO_7", label: "Métro — Ligne 7" },
    { value: "METRO_7BIS", label: "Métro — Ligne 7bis" },
    { value: "METRO_8", label: "Métro — Ligne 8" },
    { value: "METRO_9", label: "Métro — Ligne 9" },
    { value: "METRO_10", label: "Métro — Ligne 10" },
    { value: "METRO_11", label: "Métro — Ligne 11" },
    { value: "METRO_12", label: "Métro — Ligne 12" },
    { value: "METRO_13", label: "Métro — Ligne 13" },
    { value: "METRO_14", label: "Métro — Ligne 14" },
  ],

  rer: [
    { value: "RER_A", label: "RER — Ligne A" },
    { value: "RER_B", label: "RER — Ligne B" },
    { value: "RER_C", label: "RER — Ligne C" },
    { value: "RER_D", label: "RER — Ligne D" },
    { value: "RER_E", label: "RER — Ligne E" },
  ],

  tram: [
    { value: "TRAM_T1", label: "Tram — T1" },
    { value: "TRAM_T2", label: "Tram — T2" },
    { value: "TRAM_T3A", label: "Tram — T3a" },
    { value: "TRAM_T3B", label: "Tram — T3b" },
    { value: "TRAM_T4", label: "Tram — T4" },
    { value: "TRAM_T5", label: "Tram — T5" },
    { value: "TRAM_T6", label: "Tram — T6" },
    { value: "TRAM_T7", label: "Tram — T7" },
    { value: "TRAM_T8", label: "Tram — T8" },
    { value: "TRAM_T9", label: "Tram — T9" },
    { value: "TRAM_T10", label: "Tram — T10" },
    { value: "TRAM_T11", label: "Tram — T11 Express" },
    { value: "TRAM_T12", label: "Tram — T12 Express" },
    { value: "TRAM_T13", label: "Tram — T13" },
  ],

  transilien: [
    { value: "TRAIN_H", label: "Train (Transilien) — Ligne H" },
    { value: "TRAIN_J", label: "Train (Transilien) — Ligne J" },
    { value: "TRAIN_K", label: "Train (Transilien) — Ligne K" },
    { value: "TRAIN_L", label: "Train (Transilien) — Ligne L" },
    { value: "TRAIN_N", label: "Train (Transilien) — Ligne N" },
    { value: "TRAIN_P", label: "Train (Transilien) — Ligne P" },
    { value: "TRAIN_R", label: "Train (Transilien) — Ligne R" },
    { value: "TRAIN_U", label: "Train (Transilien) — Ligne U" },
  ],

  noctilien: [
    { value: "NOCT_N01", label: "Noctilien — N01 (boucle Paris)" },
    { value: "NOCT_N02", label: "Noctilien — N02 (boucle Paris)" },
    { value: "NOCT_N11", label: "Noctilien — N11" },
    { value: "NOCT_N12", label: "Noctilien — N12" },
    { value: "NOCT_N13", label: "Noctilien — N13" },
    { value: "NOCT_N14", label: "Noctilien — N14" },
    { value: "NOCT_N15", label: "Noctilien — N15" },
    { value: "NOCT_N16", label: "Noctilien — N16" },
    { value: "NOCT_N21", label: "Noctilien — N21" },
    { value: "NOCT_N22", label: "Noctilien — N22" },
    { value: "NOCT_N23", label: "Noctilien — N23" },
    { value: "NOCT_N24", label: "Noctilien — N24" },
    { value: "NOCT_N31", label: "Noctilien — N31" },
    { value: "NOCT_N32", label: "Noctilien — N32" },
    { value: "NOCT_N33", label: "Noctilien — N33" },
    { value: "NOCT_N34", label: "Noctilien — N34" },
    { value: "NOCT_N35", label: "Noctilien — N35" },
    { value: "NOCT_N41", label: "Noctilien — N41" },
    { value: "NOCT_N42", label: "Noctilien — N42" },
    { value: "NOCT_N43", label: "Noctilien — N43" },
    { value: "NOCT_N44", label: "Noctilien — N44" },
    { value: "NOCT_N45", label: "Noctilien — N45" },
    { value: "NOCT_N51", label: "Noctilien — N51" },
    { value: "NOCT_N52", label: "Noctilien — N52" },
    { value: "NOCT_N53", label: "Noctilien — N53" },
    { value: "NOCT_N61", label: "Noctilien — N61" },
    { value: "NOCT_N62", label: "Noctilien — N62" },
    { value: "NOCT_N63", label: "Noctilien — N63" },
    { value: "NOCT_N71", label: "Noctilien — N71" },
    { value: "NOCT_N122", label: "Noctilien — N122" },
    { value: "NOCT_N140", label: "Noctilien — N140" },
    { value: "NOCT_N143", label: "Noctilien — N143" },
    { value: "NOCT_N145", label: "Noctilien — N145" },
    { value: "NOCT_N151", label: "Noctilien — N151" },
  ],

  services: [
    { value: "BUS", label: "Bus (jour) — réseau très vaste (non détaillé)" },
    { value: "FUN_MONTMARTRE", label: "Funiculaire — Montmartre" },
    { value: "ORLYVAL", label: "Orlyval (liaison Orly via Antony)" },
    { value: "ROISSYBUS", label: "RoissyBus (Paris ↔ CDG)" },
    { value: "ORLYBUS", label: "OrlyBus (Paris ↔ Orly)" },
    { value: "VELIB", label: "Vélib’ (vélo en libre-service)" },
  ],
};

export const transportsParisFlat = [
  ...transportsParis.metro,
  ...transportsParis.rer,
  ...transportsParis.tram,
  ...transportsParis.transilien,
  ...transportsParis.noctilien,
  ...transportsParis.services,
];

export const transportsParisGrouped = [
  { label: "Métro", options: transportsParis.metro },
  { label: "RER", options: transportsParis.rer },
  { label: "Tram", options: transportsParis.tram },
  { label: "Train (Transilien)", options: transportsParis.transilien },
  { label: "Bus de nuit (Noctilien)", options: transportsParis.noctilien },
  { label: "Autres services", options: transportsParis.services },
];
